/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { useEffect, useRef } from 'react'
import { useFrame, useLoader } from "@react-three/fiber";
import * as THREE from 'three'
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { Mesh } from "three";

import { useGLTF, useAnimations, Environment } from '@react-three/drei'
import { useGameStore } from '../store'


export function Hisoka(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Hisoka/HisokaWAnimationWMetal.glb')
  const { actions } = useAnimations(animations, group)

  const characterState = useGameStore((state) => state.characterState);


  useEffect(() => {

    actions[characterState].reset().fadeIn(0.2).play();
    return () => {
      actions[characterState]?.fadeOut(0.2);
    };
  }, [characterState]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.02}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Character_Skin_0001" geometry={nodes.Character_Skin_0001.geometry} material={materials.Skin} skeleton={nodes.Character_Skin_0001.skeleton} />
          <skinnedMesh name="CharacterOutline001_Outline_0001" geometry={nodes.CharacterOutline001_Outline_0001.geometry} material={materials.Skin} skeleton={nodes.CharacterOutline001_Outline_0001.skeleton} />
          <skinnedMesh name="Clothing_Clothing_0001" geometry={nodes.Clothing_Clothing_0001.geometry} material={materials.Clothing} skeleton={nodes.Clothing_Clothing_0001.skeleton} />
          <skinnedMesh name="ClothingOutline_Outline_0001" geometry={nodes.ClothingOutline_Outline_0001.geometry} material={materials.Clothing} skeleton={nodes.ClothingOutline_Outline_0001.skeleton} />
          <skinnedMesh name="Eye_L_Eye_0001" geometry={nodes.Eye_L_Eye_0001.geometry} material={materials.Material} skeleton={nodes.Eye_L_Eye_0001.skeleton} />
          <skinnedMesh name="Eye_R_Eye_0001" geometry={nodes.Eye_R_Eye_0001.geometry} material={materials.Material} skeleton={nodes.Eye_R_Eye_0001.skeleton} />
          <skinnedMesh name="Hair_Hair_0001" geometry={nodes.Hair_Hair_0001.geometry} material={materials.Hair} skeleton={nodes.Hair_Hair_0001.skeleton} />
          <skinnedMesh name="HairOutline_Outline_0001" geometry={nodes.HairOutline_Outline_0001.geometry} material={materials.Hair} skeleton={nodes.HairOutline_Outline_0001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Hisoka/HisokaWAnimationWMetal.glb')
