/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jackmcm (https://sketchfab.com/Jackmcm)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/japanese-neon-street-sign-c91524e74c8c463ca3ddf71bc73911db
title: Japanese Neon Street Sign
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Neon2(props) {
  const { nodes, materials } = useGLTF('/models/Neon/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.14}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.typeBlinnSG} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Neon/scene.gltf')
