/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: K- (https://sketchfab.com/K-)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tanjiro-kamado-demon-slayer-dfebaddf7ec442cc8cf81f561fcb465b
title: tanjiro kamado demon slayer
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Tanjiro(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Tanjiro/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Fire_Driver_14" position={[-4.46, 0.1, 0]} scale={0.96} />
              <group name="katana_blade_2" position={[0, 1.13, 0]}>
                <group name="habaki_0">
                  <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.katana} />
                  <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Outline} />
                </group>
                <group name="saya_scabbard_1">
                  <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.katana} />
                  <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Outline} />
                </group>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.katana} />
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Outline} />
              </group>
              <group name="katana_blade_glow_3" position={[0, 1.13, 0]}>
                <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.katana_glow} />
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Outline.001']} />
              </group>
              <group name="GP_Layer_5">
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.GP_Outline} />
              </group>
              <group name="spiral_flame_11" position={[-0.71, 2.1, 0.18]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.05, 0.04, 0.04]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.spiral_flame} />
                <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Flame_Outline_Alpha} />
              </group>
              <group name="fire_particles_12" position={[-1.27, 2.12, -1.09]} rotation={[Math.PI, -0.33, Math.PI / 2]} scale={[0.01, 0, 0.01]}>
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.fire_particles} />
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.fire_particles} />
              </group>
              <group name="fire_breath_13" position={[0.15, 1.55, 0.05]} rotation={[0.01, 0.15, -1.57]} scale={0.04}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.flame_breath} />
                <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Flame_Outline_Alpha} />
              </group>
              <group name="Flaming_blade_15" position={[0.3, 1.83, 0.3]} rotation={[1.53, 1.42, -2.93]} scale={0.28}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.flaming_blade} />
                <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Flame_Outline_Alpha} />
              </group>
              <group name="RIG-jacket_rig_200" position={[0, 1.13, 0]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="jacket_199" />
                  <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.checkerd_jacket} skeleton={nodes.Object_34.skeleton} />
                  <skinnedMesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.Outline} skeleton={nodes.Object_35.skeleton} />
                </group>
              </group>
              <group name="rig_611" position={[0, 1.13, 0]}>
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <group name="body_607">
                    <group name="button1_201" position={[0.37, 0.28, -0.12]} rotation={[2.02, 1.04, 0.01]}>
                      <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.uniform_objects} />
                      <mesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials.Outline} />
                    </group>
                    <group name="button2_202" position={[0.38, 0.3, -0.12]} rotation={[2.09, 1.1, 0.03]}>
                      <mesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials.uniform_objects} />
                      <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.Outline} />
                    </group>
                    <group name="button3_203" position={[0.51, 0.24, -0.11]} rotation={[1.64, 0.66, 0.4]}>
                      <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.uniform_objects} />
                      <mesh name="Object_163" geometry={nodes.Object_163.geometry} material={materials.Outline} />
                    </group>
                    <group name="pocket_204" position={[0.37, 0.23, -0.17]} rotation={[1.82, 1.11, 0.08]}>
                      <mesh name="Object_165" geometry={nodes.Object_165.geometry} material={materials.uniform_objects} />
                      <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.Outline} />
                    </group>
                  </group>
                  <group name="body_objects_610">
                    <group name="legs_solidfy_outline_608" />
                    <group name="legs1_609" />
                  </group>
                  <skinnedMesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.shoe} skeleton={nodes.Object_143.skeleton} />
                  <skinnedMesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.Outline} skeleton={nodes.Object_144.skeleton} />
                  <skinnedMesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.uniform} skeleton={nodes.Object_145.skeleton} />
                  <skinnedMesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.Outline} skeleton={nodes.Object_146.skeleton} />
                  <skinnedMesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.hands} skeleton={nodes.Object_147.skeleton} />
                  <skinnedMesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.Outline} skeleton={nodes.Object_148.skeleton} />
                  <skinnedMesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.face} skeleton={nodes.Object_149.skeleton} />
                  <skinnedMesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.Outline} skeleton={nodes.Object_150.skeleton} />
                  <skinnedMesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials.legs} skeleton={nodes.Object_151.skeleton} />
                  <skinnedMesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.Outline} skeleton={nodes.Object_152.skeleton} />
                  <skinnedMesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.legs_1} skeleton={nodes.Object_153.skeleton} />
                  <skinnedMesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.Outline} skeleton={nodes.Object_154.skeleton} />
                  <skinnedMesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.earrings_img} skeleton={nodes.Object_168.skeleton} />
                  <skinnedMesh name="Object_169" geometry={nodes.Object_169.geometry} material={materials.Outline} skeleton={nodes.Object_169.skeleton} />
                  <skinnedMesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.Eyes} skeleton={nodes.Object_170.skeleton} />
                  <skinnedMesh name="Object_171" geometry={nodes.Object_171.geometry} material={materials.Outline} skeleton={nodes.Object_171.skeleton} />
                  <skinnedMesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.mouth_and_ears} skeleton={nodes.Object_172.skeleton} />
                  <skinnedMesh name="Object_173" geometry={nodes.Object_173.geometry} material={materials.Outline} skeleton={nodes.Object_173.skeleton} />
                  <skinnedMesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.eye_brows__eye_lashes} skeleton={nodes.Object_174.skeleton} />
                  <skinnedMesh name="Object_175" geometry={nodes.Object_175.geometry} material={materials.Outline} skeleton={nodes.Object_175.skeleton} />
                  <skinnedMesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.hair} skeleton={nodes.Object_176.skeleton} />
                  <skinnedMesh name="Object_177" geometry={nodes.Object_177.geometry} material={materials.Outline} skeleton={nodes.Object_177.skeleton} />
                  <skinnedMesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.uniform_objects} skeleton={nodes.Object_178.skeleton} />
                  <skinnedMesh name="Object_179" geometry={nodes.Object_179.geometry} material={materials.Outline} skeleton={nodes.Object_179.skeleton} />
                  <skinnedMesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.belt} skeleton={nodes.Object_180.skeleton} />
                  <skinnedMesh name="Object_181" geometry={nodes.Object_181.geometry} material={materials.Outline} skeleton={nodes.Object_181.skeleton} />
                  <skinnedMesh name="Object_183" geometry={nodes.Object_183.geometry} material={materials.Outline} skeleton={nodes.Object_183.skeleton} />
                  <skinnedMesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.Outline} skeleton={nodes.Object_184.skeleton} />
                  <skinnedMesh name="Object_185" geometry={nodes.Object_185.geometry} material={materials.Outline} skeleton={nodes.Object_185.skeleton} />
                  <skinnedMesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials.Outline} skeleton={nodes.Object_186.skeleton} />
                  <skinnedMesh name="Object_187" geometry={nodes.Object_187.geometry} material={materials.Outline} skeleton={nodes.Object_187.skeleton} />
                  <skinnedMesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials.Outline} skeleton={nodes.Object_188.skeleton} />
                  <skinnedMesh name="Object_189" geometry={nodes.Object_189.geometry} material={materials.Outline} skeleton={nodes.Object_189.skeleton} />
                  <skinnedMesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials.Outline} skeleton={nodes.Object_190.skeleton} />
                  <skinnedMesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials.shoe} skeleton={nodes.Object_192.skeleton} />
                  <skinnedMesh name="Object_193" geometry={nodes.Object_193.geometry} material={materials.Outline} skeleton={nodes.Object_193.skeleton} />
                </group>
              </group>
              <group name="wooden_box_rig_639">
                <group name="GLTF_created_2">
                  <primitive object={nodes.GLTF_created_2_rootJoint} />
                  <group name="wooden_box_638" />
                  <skinnedMesh name="Object_600" geometry={nodes.Object_600.geometry} material={materials.wooden_box} skeleton={nodes.Object_600.skeleton} />
                  <skinnedMesh name="Object_601" geometry={nodes.Object_601.geometry} material={materials.Outline} skeleton={nodes.Object_601.skeleton} />
                  <skinnedMesh name="Object_602" geometry={nodes.Object_602.geometry} material={materials.wooden_box_2} skeleton={nodes.Object_602.skeleton} />
                  <skinnedMesh name="Object_603" geometry={nodes.Object_603.geometry} material={materials.Outline} skeleton={nodes.Object_603.skeleton} />
                  <skinnedMesh name="Object_604" geometry={nodes.Object_604.geometry} material={materials.wooden_box_straps} skeleton={nodes.Object_604.skeleton} />
                  <skinnedMesh name="Object_605" geometry={nodes.Object_605.geometry} material={materials.Outline} skeleton={nodes.Object_605.skeleton} />
                  <skinnedMesh name="Object_606" geometry={nodes.Object_606.geometry} material={materials.wooden_box_metal} skeleton={nodes.Object_606.skeleton} />
                  <skinnedMesh name="Object_607" geometry={nodes.Object_607.geometry} material={materials.Outline} skeleton={nodes.Object_607.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Tanjiro/scene.gltf')
